export APP_NAME := filestash
export VERSION := $(shell git describe --tags --always --dirty 2>/dev/null || echo dev)
export COMMIT := $(shell git rev-parse --short HEAD 2>/dev/null || echo none)
export DATE := $(shell date -u +%Y-%m-%d)
export COMPOSE_FILE := docker/docker-compose.yml

LDFLAGS := -ldflags "-X main.version=$(VERSION) \
					-X main.commit=$(COMMIT) \
					-X main.date=$(DATE)"
GOFLAGS := -trimpath
BUILD_TAGS := fts5
DIST := dist
CMD := ./cmd/main.go

.PHONY: all init generate build clean test lint fmt vet race

all: build

init:
	go mod tidy
	go mod download

generate:
	go generate -x ./server/...

build: generate
	mkdir -p $(DIST)
	go build $(GOFLAGS) $(LDFLAGS) --tags "$(BUILD_TAGS)" \
		-o $(DIST)/$(APP_NAME) $(CMD)

test:
	go test ./...

race:
	go test -race ./...

vet:
	go vet ./...

fmt:
	@git grep -Lz 'Code generated by' -- '*.go' \
	| xargs -0 gofmt -w

lint:
	golangci-lint run ./...

sec:
	gosec ./...

cover:
	go test -coverprofile=coverage.out ./...
	go tool cover -html=coverage.out

ci: fmt vet lint sec race test cover

clean:
	rm -rf $(DIST)
	go clean

docker-build:
	docker compose --progress=plain build

docker-run:
	docker compose up -d

docker-logs:
	docker compose logs -f

docker-down:
	docker compose down

docker-ps:
	docker compose ps
