export APP_NAME := filestash
export VERSION := $(shell git describe --tags --always --dirty 2>/dev/null || echo dev)
export COMMIT := $(shell git rev-parse --short HEAD 2>/dev/null || echo none)
export DATE := $(shell date -u +%Y-%m-%d)
export COMPOSE_FILE := docker/docker-compose.yml

LDFLAGS := -ldflags "-X main.version=$(VERSION) \
					-X main.commit=$(COMMIT) \
					-X main.date=$(DATE)"
GOFLAGS := -trimpath
BUILD_TAGS := fts5
DIST := dist
CMD := ./cmd/main.go

.PHONY: all init generate build clean test lint fmt vet race help ci sec cover docker-% frontend-%

help: # Show this help
	@grep -E '^[a-zA-Z_-]+:.*?#+ .*$$' $(MAKEFILE_LIST) \
	| awk 'BEGIN {FS = ":.*?#+ "}; {printf "\033[36m%-23s\033[0m %s\n", $$1, $$2}'

init: # Initialize go modules (tidy & download dependencies)
	go mod tidy
	go mod download

generate: # Generate code with go generate
	go generate -x ./server/...

build: generate # Build the application binary
	mkdir -p $(DIST)
	go build $(GOFLAGS) $(LDFLAGS) --tags "$(BUILD_TAGS)" \
		-o $(DIST)/$(APP_NAME) $(CMD)

test: # Run all tests
	go test ./...

race: # Run all tests with race detector
	go test -race ./...

vet: # Run go vet to check for suspicious constructs
	go vet ./...

fmt: # Format Go code (excluding generated files)
	@git grep -Lz 'Code generated by' -- '*.go' \
	| xargs -0 gofmt -w

lint: # Run linter (golangci-lint)
	golangci-lint run ./...

sec: # Run security checks (gosec)
	gosec ./...

cover: # Generate test coverage report
	go test -coverprofile=coverage.out ./...
	go tool cover -html=coverage.out

ci: fmt vet lint sec race test cover # Run all checks for CI

clean: # Remove build artifacts and clean Go cache
	rm -rf $(DIST)
	go clean

docker-build: # Build docker containers
	docker compose --progress=plain build

docker-run: # Start docker containers in background
	docker compose up -d

docker-logs: # Follow logs from docker containers
	docker compose logs -f

docker-down: # Stop and remove docker containers
	docker compose down

docker-ps: # List running docker containers
	docker compose ps

frontend-%: # Run a Make target in the frontend (public) directory, e.g. install, lint, check
	$(MAKE) -C public $*
