services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      args:
        VERSION: ${VERSION}
        COMMIT: ${COMMIT}
        DATE: ${DATE}
    image: "${APP_NAME}:${VERSION}"
    container_name: filestash
    restart: unless-stopped
    environment:
      - APPLICATION_URL=
      - CANARY=true
    ports:
      - "127.0.0.1:8334:8334"
    volumes:
      - filestash:/app/data/state/
    init: true

volumes:
  filestash: {}
